# @package _global_
# Circle packing optimizer definition

optimizer:
  initial_optimizer: configs/eve/optimizer/circle_packing/initial_optimizer
  evaluation:
    _target_: scaling_evolve.algorithms.eve.populations.evaluators.elo.ScalarEloEvaluator
    k_factor: 32.0
    initial_score:
      elo: 1500.0
