# @package _global_

label: ""
run_timestamp: ${now:%Y%m%d_%H%M%S_%f}
run_id: ${eve_run_id:${run_timestamp},${label}}
resume_from: null
resume_iteration: null
import_from: null
run_root: ${eve_run_root:${resume_from},${oc.env:PWD},${application.name},${run_id}}

hydra:
  run:
    dir: ${run_root}
  job_logging:
    handlers:
      file:
        filename: ${hydra.runtime.output_dir}/runner.log
